### PR TITLE
Mac installer menu bar icon not set to "processing" while setup is running

### LINKED ISSUE #187: Mac installer menu bar icon not set to "processing" while setup is running.
**Branch:** `master` 

**Expected behaviour:** Menu bar icon must set to "processing" while setup is running.

**Current behaviour:**  Menu bar icon not set to "processing" while setup is running.

**Steps to reproduce:**
 1. Launch the `kalite monitor app`
 2. Click the apply button at the preferences menu.
 3. Notice the menu bar icon is set back to "ready" and not "processing", the "Start KA-Lite" menu is available.
 4. Clicking on the "Start KA-Lite" menu option shows the "KA-Lite is still processing" alert.

### PR DESCRIPTION
**Pull request by amodia**
@cpauya this fixes #187

### CODE REVIEW

File: osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m [hunk 1]
```diff
@@ -352,28 +362,24 @@ - (enum kaliteStatus)checkRunTask:(NSNotification *)aNotification{
...
-            self.kaliteIsRunning = NO;
-            
             // If command is not "status", run `kalite status` to get status of ka-lite.
             // We need this check because this may be called inside the monitor timer.
             NSLog(@"Fetching `kalite status`...");
-            if ( [taskArguments containsObject: @"manage"] ) {
-                [self showStatus:self.status];
-            }
+            [self showStatus:self.status];
             [self runKalite:@"status"];
```
Comment (cpauya) [inline osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m]: Redundant code, use the `getKaliteStatus()` function below at roughly LOC:1087.

**Comment by cpauya** [comment]
@amodia I will accepting this PR so I can merge your fixes but you need to file another issue re our findings on "status check must increment the process counter and set the icon properly".
