### PR TITLE
KA Lite application must not load if `kalite` executable is not found.

### LINKED ISSUE #327: KA Lite application must not load if `kalite` executable is not found.
**Branch:** `develop` (OS x installer)
**Current behavior:** KA Lite application will load even if `kalite` executable is not found.
**Expected behavior:** KA Lite application must not load if `kalite` executable is not found.

**Steps to reproduce:**
 1. Install the OS x KA Lite application.
 2. Remove the kalite executable at `/usr/local/bin/kalite`
 3. Launch the KA Lite application.

**Checklist:**
 
- [x] Notify user that kalite executable is not found
- [x] Log the error message for reference
- [x] Don't load the application

### PR DESCRIPTION
**Pull request by amodia**
@cpauya this fixes #327 

I created an alert dialog to notify and will not load the KA Lite application if kalite executable is not found,

### CODE REVIEW

File: osx/KA-Lite/KA-Lite/AppDelegate.m [hunk 1]
```diff
@@ -382,6 +385,14 @@ BOOL confirm(NSString *message) {
 }
 
 
+void alertDialog(NSString *message) {
```
Comment (cpauya) [inline osx/KA-Lite/KA-Lite/AppDelegate.m]: @amodia Re-use the `alert()` function in the code.

File: osx/KA-Lite/KA-Lite/AppDelegate.m [hunk 2]
```diff
@@ -43,58 +43,61 @@ - (BOOL)applicationShouldHandleReopen:(NSApplication *)theApplication hasVisible
...
+    
+    if (!pathExists(kalite)) {
+        NSLog(@"kalite executable is not found.");
+        [self showStatus:statusFailedToStart];
+        alertDialog(@"Kalite executable is not found. You need to reinstall the KA Lite application.");
+        //The application must terminate if kalite executable is not found.
+        [[NSApplication sharedApplication] terminate:nil];
+    } else
+    
+    {
```
Comment (cpauya) [inline osx/KA-Lite/KA-Lite/AppDelegate.m]: Fix the format for the `if.. else..` here.

Comment (cpauya) [inline osx/KA-Lite/KA-Lite/AppDelegate.m]: You can actually just remove the `else` already because you are terminating the app anyway.

File: osx/KA-Lite/KA-Lite/AppDelegate.m [hunk 3]
```diff
@@ -43,58 +43,61 @@ - (BOOL)applicationShouldHandleReopen:(NSApplication *)theApplication hasVisible
...
-
-        NSString *kalite = getUsrBinKalite();
-        if (!pathExists(kalite)) {
-            NSLog(@"kalite executable is not found, must show preferences.");
-            mustShowPreferences = true;
-            [self showStatus:statusFailedToStart];
-            showNotification(@"Kalite executable is not found. You need to reinstall the KA Lite application.");
-            
-        } else {
+    NSString *kalite = getUsrBinKalite();
```
Comment (cpauya) [inline osx/KA-Lite/KA-Lite/AppDelegate.m]: Can you rename the `getUsrBinKalite()` function into `getKaliteExecutable()`?  It's confusing.

File: osx/KA-Lite/KA-Lite/AppDelegate.m [hunk 4]
```diff
@@ -43,58 +43,61 @@ - (BOOL)applicationShouldHandleReopen:(NSApplication *)theApplication hasVisible
...
+    
+        [self.kaliteDataHelp setToolTip:@"This will set the KALITE_HOME environment variable to the selected KA Lite data location. \n \nClick the 'Apply' button to save your changes and click the 'Start KA Lite' button to use your new data location. \n \nNOTE: To use your existing KA Lite data, manually copy it to the selected KA Lite data location."];
+
+        // Set the default status.
+        self.status = statusCouldNotDetermineStatus;
+        [self getKaliteStatus];
+    
+        // We need to show preferences if the following does not exist:
+        // 1. database does not exist
+        // 2. symlinked `kalite` executable
```
Comment (cpauya) [inline osx/KA-Lite/KA-Lite/AppDelegate.m]: Remove this comment, it doesn't apply anymore.

**Comment by cpauya** [comment]
Tested and demoed, merging.
